### ISSUE TITLE
status

### ISSUE THREAD

**Issue by tiralonghipol** [zauberflote1/voxlSyncVINS#1]
hei! is this updated? we are trying to achieve something similar
thanks!

https://forum.modalai.com/topic/3245/voxl-open-vins-server-how-to-use-overall-questions-ros-ros2-findings/4

**Comment by zauberflote1** [comment]
Greetings, 
This is currently not updated, but I can update the repo.
Which SDK compatible do you need?

Also, I am currently working on a way to merge both IMU ROS and the classic IMU server from ModalAI, so you can use QVIO using the IMU FIFO buffer and read single readings for other classic VINS. Anyways, feel free to ask, I am happy to help

**Comment by tiralonghipol** [comment]
nice! we are using 1.3.3
for now just increasing the queue size to 25 in voxl_mpa_to_ros driver seems to solve the issue btw
but we were curious about your implementation driver level

**Comment by zauberflote1** [comment]
The repo has been updated. Please feel free to share your thoughts and questions.
